server:
  port: 1997

spring:
  # 数据源
  datasource:
    dynamic:
      primary: master
      datasource:
#        master:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://121.40.229.114:3306/tester_plat?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#          username: dujun
#          password: test1997
        master:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://118.31.184.240:3306/tester_plat?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            username: root
            password: 3wHNY2Bq
        qsTest:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://118.31.184.240:3306?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            username: root
            password: 3wHNY2Bq
      druid:
        test-on-borrow: true
        test-while-idle: true
        init-connection-sqls: set names utf8mb4
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**
  freemarker:
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # redis配置
  redis:
    database: 0
    host: 120.55.125.94
    port: 6379
    connect-timeout: 3000
    password: 4A$2QgF4g7Orz*


# mybatis-plus
mybatis-plus:
  # 打印sql执行结果
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/*Mapper.xml

  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-not-delete-value: 0
      logic-delete-value: 1

# 简洁配置-不打印sql执行结果
logging:
  level:
    com:
      dujun:
        springboot:
          DEBUG
# 测试环境
test:
  domain:
    qyh: "http://testadmin.qyhnet.com"
  redis:
    qyh:
      ip : "120.55.125.94"
      password : "4A$2QgF4g7Orz*"

# 线上环境
online:
  domain:
    qyh: "http://testadmin.qyhnet.com"

#rocketmq:
#  name-server: 121.40.229.114:9876
#  producer:
#    group: springBootGroup

